apiVersion: v1
kind: Service
metadata:
  name: dishub
  namespace: coaster
  labels:
    app: dishub
spec:
  selector:
    app: dishub
  ports:
  - protocol: TCP
    name: api
    port: 8080
    targetPort: 8080
  type: ClusterIP
