apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dishub
  namespace: coaster
  labels:
    app: dishub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dishub
  template:
    metadata:
      labels:
        app: dishub
    spec:
      serviceAccountName: dishub
      containers:
        - name: dishub
          image: coasterfreakde/dishub-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080